name: Pulumi
on:
  push:
    branches:
      - main
    paths:
      - infra/project/**
      - '!README.md' # to ignore Readme.md file
      
  workflow_dispatch:
#     inputs:
#       description:
#         description: 'Manual Trigger' 
#   push:
#     branches:
#       - main
#     paths:
#       - infra/project/**
jobs:
  
  update:
    name: budibase-infra
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./infra/project/
    
    strategy:
      matrix:
        node-version: [19.8.1]
    steps: 
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
#           node-version-file: package.json
            node-version: ${{ matrix.node-version }}
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: ${{ secrets.AWS_REGION }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - run: npm install
      - uses: pulumi/actions@v3
        with:
          work-dir: ./infra/project/
          command: up
          stack-name: dev # When using an individual account, only use stack-name.
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
